package com.austincreations.rollforthegalaxy.tile;

public enum DevelopTileEffect {
    EXPLORE_FOUR_CREDITS_WHEN_STOCKING_WITH_A_YELLOW_DIE,
    EXPLORE_MAY_PLACE_TILES_ON_TOP_OF_STACKS,
    PRODUCE_ONE_CREDIT_FOR_EACH_BLUE_DIE_ON_A_WORLD_AT_END_OF_PHASE,
    SHIP_ONE_CREDIT_FOR_EVERY_TWO_RED_DICE_IN_CITIZENRY_AT_END_OF_PHASE
}
