package com.austincreations.rollforthegalaxy.tile;

public enum FactionTile {
    SPACE_PIRACY_HIDDEN_FORTRESS,
    ALIEN_ARCHAEOLOGY_ALIEN_ROSETTA_STONE_WORLD,
    CONSUMER_MARKETS_SPACE_MALL,
    IMPROVED_RECONNAISSANCE_WORMHOLE_STATION,
    GENETICS_LAB_THE_LAST_OF_THE_GNARSSH
}
