package com.austincreations.rollforthegalaxy;

public enum GameTile {
    ADVANCED_LOGISTICS_DESIGNER_SPECIES_ULTD,
    EXECUTIVE_POWER_TRADING_WORLD,
    GALACTIC_DEMAND_DESERTED_ALIEN_OUTPOST,
    GALACTIC_RECYCLING_ALIEN_ROBOT_SCOUT_SHIP,
    GALACTIC_RESERVES_REBEL_HIDEOUT,
    HOMEWORLD_PATRIOTISM_PLAGUE_WORLD,
    ISOLATION_POLICY_PLANETARY_NEBULA,
    SPACE_DOCKS_ARMAMENTS_WORLD,
    TRADE_LEVIES_COMET_ZONE
}
